languageCode:           "ru-ru"
title:                  "Bootstrap"
baseURL:                "https://getbootstrap.su"

security:
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_
      - NETLIFY

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

publishDir:             "_site"

module:
  mounts:
    - source:           dist
      target:           static/docs/5.3/dist
    - source:           site/assets
      target:           assets
    - source:           site/content
      target:           content
    - source:           site/data
      target:           data
    - source:           site/layouts
      target:           layouts
    - source:           site/static
      target:           static
    - source:           site/static/docs/5.3/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           site/static/docs/5.3/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  subtitle:             "Самая популярная библиотека HTML, CSS и JS в мире. Перевод официальной документации Bootstrap. Bootstrap на русском."
  description:          "Мощный, расширяемый и многофункциональный интерфейсный инструментарий. Создавайте и настраивайте с помощью Sass, используйте готовую систему сеток и компоненты и воплощайте проекты в жизнь с помощью мощных плагинов JavaScript."
  authors:              "Марк Отто, Джейкоб Торнтон и контрибьюторы Bootstrap"

  current_version:      "5.3.0-alpha2"
  current_ruby_version: "5.3.0-alpha2"
  docs_version:         "5.3"
  rfs_version:          "v9.0.6"
  original_url:         "https://getbootstrap.com"
  github_org:           "https://github.com/twbs"
  github_ru:            "https://github.com/ruBootstrap"
  telegram_ru:          "https://t.me/getbootstrap_ru"
  repo:                 "https://github.com/twbs/bootstrap"
  repo_ru:              "https://github.com/ruBootstrap/bootstrap"
  telegram:             "https://t.me/getbootstrap_ru"
  twitter:              "getbootstrap"
  opencollective:       "https://opencollective.com/bootstrap"
  blog:                 "https://blog.getbootstrap.com/"
  blog_ru:              "https://blog.getbootstrap.su/"
  themes:               "https://themes.getbootstrap.com/"
  icons:                "https://icons.getbootstrap.com/"
  icons_ru:             "https://icons.getbootstrap.su/"
  cheatsheet_ru:        "https://cheatsheet.getbootstrap.su/"
  swag:                 "https://cottonbureau.com/people/bootstrap"

  download:
    source:             "https://github.com/twbs/bootstrap/archive/v5.3.0-alpha2.zip"
    dist:               "https://github.com/twbs/bootstrap/releases/download/v5.3.0-alpha2/bootstrap-5.3.0-alpha2-dist.zip"
    dist_examples:      "https://github.com/twbs/bootstrap/releases/download/v5.3.0-alpha2/bootstrap-5.3.0-alpha2-examples.zip"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:              "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css"
    css_hash:         "sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp"
    css_rtl:          "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.rtl.min.css"
    css_rtl_hash:     "sha384-5/ZcxA7Dub2FNG09dHw8CHmPN7Fz6ASlweagj0nuXjmMyupgH9n9F5Hd926zsu3/"
    js:               "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.min.js"
    js_hash:          "sha384-heAjqF+bCxXpCWLa6Zhcp4fu20XoNIA98ecBC1YkdXhszjoejr5y9Q77hIrv8R9i"
    js_bundle:        "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"
    js_bundle_hash:   "sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N"
    popper:           "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    popper_hash:      "sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
    popper_esm:       "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/esm/popper.min.js"

  anchors:
    min: 2
    max: 5
